### ISSUE TITLE
WorldEdit ignores other locations of SteamLibrary.

### ISSUE THREAD

**Issue by MrSoup678** [nesrak1/HKWorldEdit2#11]
HKEdit expects the game to be at C:\Program Files (x86)\Steam\steamapps\, completely ignoring all other possible locations. Use libraryfolder.vdf in the directory listed above to check all locations.

**Comment by nesrak1** [comment]
It definitely uses libraryfolders.vdf: https://github.com/nesrak1/HKWorldEdit2/blob/master/Assets/Editor/SteamHelper.cs#L31

**Comment by MrSoup678** [comment]
And yet it didn't find my Installation. I'll check why it is failing.
EDIT: I might have a theory. I too had problems with that vdf file and found out, that its format was changed. That change was undocumented. I'll check shortly if that's the case.

**Comment by MrSoup678** [comment]
That is indeed the case. I've already rewritten necessary function. To fix said bug (and to future-proof) I've added vdf library. The bug is fixed on my end.
