### ISSUE TITLE
Scenes containing Broken Vessel & Lost Kin fail to load.

### ISSUE THREAD

**Issue by EnderOnryo** [nesrak1/HKWorldEdit2#16]
Scenes `Abyss_19`, `Dream_03_Infected_Knight`, `GG_Broken_Vessel`, & `GG_Lost_Kin` fail to load with the error of `NullReferenceException: Object reference not set to an instance of an object` displaying.

**Comment by nesrak1** [comment]
Let me know if the latest code works.

**Comment by EnderOnryo** [comment]
It does, they booted up just fine.
