### ISSUE TITLE
Can't load Scene  

### ISSUE THREAD

**Issue by RemDust** [nesrak1/HKWorldEdit2#17]
Hey there, thanks for the hard work.
At the moment except for scene 420 (I haven't tested all of them) I cannot load any scene (Unity 2020.2.2.f1, mac os)

Here is the error that pops up when I try to load :

NullReferenceException: Object reference not set to an instance of an object
Assets.Bundler.ReferenceCrawlerEditor.ConvertToAssetID (AssetsTools.NET.Extra.AssetsFileInstance inst, System.Int32 fileId, System.Int64 pathId) (at Assets/Editor/Bundler/ReferenceCrawlerEditor.cs:266)
Assets.Bundler.ReferenceCrawlerEditor.SetReferencesRecurse (AssetsTools.NET.Extra.AssetsFileInstance inst, AssetsTools.NET.AssetTypeValueField field) (at Assets/Editor/Bundler/ReferenceCrawlerEditor.cs:122)
Assets.Bundler.ReferenceCrawlerEditor.SetReferencesRecurse (AssetsTools.NET.Extra.AssetsFileInstance inst, AssetsTools.NET.AssetTypeValueField field) (at Assets/Editor/Bundler/ReferenceCrawlerEditor.cs:133)
Assets.Bundler.ReferenceCrawlerEditor.SetReferencesRecurse (AssetsTools.NET.Extra.AssetsFileInstance inst, AssetsTools.NET.AssetTypeValueField field) (at Assets/Editor/Bundler/ReferenceCrawlerEditor.cs:135)
Assets.Bundler.ReferenceCrawlerEditor.SetReferencesRecurse (AssetsTools.NET.Extra.AssetsFileInstance inst, AssetsTools.NET.AssetTypeValueField field) (at Assets/Editor/Bundler/ReferenceCrawlerEditor.cs:135)
Assets.Bundler.ReferenceCrawlerEditor.SetReferencesRecurse (AssetsTools.NET.Extra.AssetsFileInstance inst, AssetsTools.NET.AssetTypeValueField field) (at Assets/Editor/Bundler/ReferenceCrawlerEditor.cs:135)
Assets.Bundler.ReferenceCrawlerEditor.SetReferences (AssetsTools.NET.Extra.AssetsFileInstance inst, AssetsTools.NET.AssetFileInfoEx inf) (at Assets/Editor/Bundler/ReferenceCrawlerEditor.cs:48)
Assets.Bundler.Loader.GenerateLevelFiles (AssetsTools.NET.Extra.AssetsManager am, AssetsTools.NET.Extra.AssetsFileInstance inst) (at Assets/Editor/Bundler/Loader.cs:55)
Assets.Bundler.Loader.GenerateLevelFiles (System.String levelPath) (at Assets/Editor/Bundler/Loader.cs:26)
SceneLoad.OpenScene (System.String path) (at Assets/Editor/SceneLoad.cs:40)
SceneLoad.CreateScene () (at Assets/Editor/SceneLoad.cs:16)

**Comment by nesrak1** [comment]
Same as #3. From that issue:

> MacOS users should copy `Contents/Resources/unity default resources` to `Contents/Resources/Data/Resources/`

I should probably put a note in the README at some point.
