### ISSUE TITLE
Could not find file cldb.dat

### ISSUE THREAD

**Issue by ForestDango** [nesrak1/HKWorldEdit2#18]
![image](https://user-images.githubusercontent.com/98653849/196074293-854c3118-c3ff-466f-a616-49d5de481be0.png)

  I think i have imported cldb.dat but it still Log Error.
  Is there any other assets I forgot to import?

**Comment by nesrak1** [comment]
It comes with the project, so unless you deleted it there shouldn't be an issue. Anyways, cldb.dat isn't an asset, is sits in the project root, so putting it in the Assets folder isn't going to work as the error message tells you.

**Comment by ForestDango** [comment]
Well... It still  fail to work out after I deleted the cldb.dat
![105dec584afd781d07db64467cdcfde](https://user-images.githubusercontent.com/98653849/197683396-03fad496-2190-4768-9dd1-860e644371d8.png)

**Comment by nesrak1** [comment]
This isn't an HKWE issue, if there's not a cldb.dat file in `C:\Users\admin\HKWorldScene2.0\`, then you need to put one there. The error says exactly where it's looking.

**Comment by ForestDango** [comment]
Oh! Forgive my poor understanding and finalIy succeed in open the Scene!
I would be very grateful for your HKEW and HollowKnightFSM work😀
