### ISSUE TITLE
Shader report Error after Loading Scenes

### ISSUE THREAD

**Issue by ForestDango** [nesrak1/HKWorldEdit2#19]
There is a shader Error after loading a scene.
All shaders will become Hidden/InternalErrorShader
![1667016031387](https://user-images.githubusercontent.com/98653849/198812997-1e7bd8ef-7af4-4d7e-a5f2-431e1059cad3.png)
![1667016031410](https://user-images.githubusercontent.com/98653849/198813000-04cb64eb-dbec-4d36-af4f-e23ea3e00d13.png)

**Comment by nesrak1** [comment]
Do all scenes look like this or just on level1?

**Comment by ForestDango** [comment]
Yes.All scenes look like this.
![1667097059399](https://user-images.githubusercontent.com/98653849/198859930-433538bd-da12-4fb5-8139-e473144ca565.png)
![1667097114121](https://user-images.githubusercontent.com/98653849/198859932-9b969f74-9e39-479d-bca3-839aab749ddd.png)
![1667097184292](https://user-images.githubusercontent.com/98653849/198859934-86b8c6b9-6061-4b98-8edb-4b57b16e9536.png)

**Comment by nesrak1** [comment]
I can't reproduce. I pulled master and ran it on a few scenes. Are you changing any code or files? You made an issue earlier where there wasn't a cldb and that wouldn't have happened on stock code.

**Comment by ForestDango** [comment]
Yeh,I am sure that I am not changing any code or files and also I have imported the cldb.Whatever I create a new project this issue still exist.

And I would show you my Project folder.

![1667269908294](https://user-images.githubusercontent.com/98653849/199145868-de0002bd-2385-419d-9a85-632d9864e670.png)
![1667269901865](https://user-images.githubusercontent.com/98653849/199145876-b36936ce-277f-4b62-82f4-2bdd0528675e.png)

**Comment by nesrak1** [comment]
Why are you "creating a new project"? You just need to [download the repo](https://github.com/nesrak1/HKWorldEdit2/archive/refs/heads/master.zip), unzip it, and tell unity to open the folder you go after unzipping as a project. You don't need to "import the cldb either". It's already in the zip. I don't understand how you could possibly be missing it.

**Comment by ForestDango** [comment]
Sorry,I misunderstood what you said and the problem has been solved now.Thanks for your extact explain
